# -*- coding: utf-8 -*-
"""dashboard_Valiotti_Analytics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w5ng7o0-8uG37xOjOeqIHJ9LJc6fs8CB
"""

import sys
!pip install dash
!pip install plotly

import pandas as pd
from dash import Dash, dcc, html
from dash.dependencies import Input, Output

df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vR79g42LS5Ns2qHNq94NL9YslQnh9QOL4UmguH0tCn36YY_X0D5BNJ03a6UlR3ehgvDLoyF2mPC-p3U/pub?output=csv',index_col=0)
df.head()

"""## Предобработка данных"""

df.columns = df.columns.str.lower()

df.info()

"""Необходимо изменить тип данных в колонках  в __year_of_release__ с float 64 на ..., __user_scor__ object на float64"""

df = df.dropna()

df =  df.query('year_of_release >= 2000.0').reset_index()

df['year_of_release'] = pd.to_datetime(df['year_of_release'], format='%Y')
df.head()

"""__Подготовка датасета к построению дашборда.__

- Добавим индексы

- Удалим проекты с датой выхода ранее 2000 года

- Удалим проекты, в которых есть пропуски в любой и колонок
"""

